package ctrmap.creativestudio.nitroplugin;

import ctrmap.formats.ntr.nitrowriter.nsbca.NSBCAExportSettings;
import java.awt.Frame;
import xstandard.gui.DialogOptionRemember;

public class NSBCAExportDialog extends javax.swing.JDialog {

	private NSBCAExportSettings result;
	
	public NSBCAExportDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);
		
		DialogOptionRemember.setRememberedCheckbox(btnTargetAllBones);
	}
	
	public NSBCAExportSettings getResult() {
		return result;
	}
	
	public static NSBCAExportSettings getExportSettings(Frame parent){
		NSBCAExportDialog dlg = new NSBCAExportDialog(parent, true);
		dlg.setVisible(true);
		return dlg.getResult();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
	 * code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTargetAllBones = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Export NSBCA");

        btnTargetAllBones.setSelected(true);
        btnTargetAllBones.setText("Target all bones (bugfix)");

        jLabel1.setText("Enhancements/fixes");

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnTargetAllBones))
                    .addComponent(jLabel1))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTargetAllBones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        DialogOptionRemember.putRememberedCheckbox(btnTargetAllBones);

        result = new NSBCAExportSettings();
		result.forceTargetAllJoints = btnTargetAllBones.isSelected();

        dispose();
    }//GEN-LAST:event_btnExportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JCheckBox btnTargetAllBones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
