package ctrmap.creativestudio.nitroplugin;

import ctrmap.formats.ntr.nitrowriter.nsbmd.NSBMDExportSettings;
import xstandard.gui.DialogOptionRemember;
import xstandard.gui.components.ComponentUtils;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class NSBMDExportDialog extends javax.swing.JDialog {

	private NSBMDExportSettings result = null;

	public NSBMDExportDialog(java.awt.Frame parent, boolean modal) {
		this(parent, modal, true);
	}
	
	public NSBMDExportDialog(java.awt.Frame parent, boolean modal, boolean enableTexOnly) {
		super(parent, modal);
		initComponents();

		setLocationRelativeTo(parent);
		
		ActionListener checkboxListener = (ActionEvent e) -> {
			setModelOrTextureCheckboxEnabled();
		};

		btnIncludeModelsAndTextures.addActionListener(checkboxListener);
		btnIncludeModelsOnly.addActionListener(checkboxListener);
		btnIncludeTexturesOnly.addActionListener(checkboxListener);
		
		btnIncludeTexturesOnly.setEnabled(enableTexOnly);

		DialogOptionRemember.selectRememberedRBtnPos(includedResourcesGroup);

		DialogOptionRemember.setRememberedCheckbox(btnCreatePolystrips);
		DialogOptionRemember.setRememberedCheckbox(btnEnableMinPrimitiveCount);
		DialogOptionRemember.setRememberedCheckbox(btnPreferVColOverNormal);
		DialogOptionRemember.setRememberedCheckbox(btnIsOmitUnusedTextures);
		DialogOptionRemember.setRememberedCheckbox(btnJointsAsVisgroups);
		
		DialogOptionRemember.setRememberedSpinnerInt(minPrimitiveCount, "nsbmd_MinPrimitiveCount");
		
		if (btnIncludeTexturesOnly.isSelected() && !enableTexOnly){
			btnIncludeModelsAndTextures.setSelected(true);
		}
		
		setModelOrTextureCheckboxEnabled();
	}

	private void setModelOrTextureCheckboxEnabled() {
		boolean isMdl = btnIncludeModelsOnly.isSelected() || btnIncludeModelsAndTextures.isSelected();
		boolean isTex = btnIncludeTexturesOnly.isSelected() || btnIncludeModelsAndTextures.isSelected();

		ComponentUtils.setComponentsEnabled(isMdl, btnCreatePolystrips, btnPreferVColOverNormal);
		btnEnableMinPrimitiveCount.setEnabled(btnCreatePolystrips.isSelected() && isMdl);
		minPrimitiveCount.setEnabled(btnEnableMinPrimitiveCount.isSelected() && isMdl);
		btnIsOmitUnusedTextures.setEnabled(isMdl && isTex);
		btnJointsAsVisgroups.setEnabled(isMdl);
	}

	public NSBMDExportSettings getResult() {
		return result;
	}
	
	public static NSBMDExportSettings getExportSettings(Frame parent){
		NSBMDExportDialog dlg = new NSBMDExportDialog(parent, true);
		dlg.setVisible(true);
		return dlg.getResult();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        includedResourcesGroup = new javax.swing.ButtonGroup();
        includedResourcesLabel = new javax.swing.JLabel();
        btnIncludeModelsAndTextures = new javax.swing.JRadioButton();
        btnIncludeModelsOnly = new javax.swing.JRadioButton();
        btnIncludeTexturesOnly = new javax.swing.JRadioButton();
        additionalOptionsLabel = new javax.swing.JLabel();
        btnCreatePolystrips = new javax.swing.JCheckBox();
        btnPreferVColOverNormal = new javax.swing.JCheckBox();
        btnExport = new javax.swing.JButton();
        minPrimitiveCount = new javax.swing.JSpinner();
        btnEnableMinPrimitiveCount = new javax.swing.JCheckBox();
        btnIsOmitUnusedTextures = new javax.swing.JCheckBox();
        btnJointsAsVisgroups = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Export NSBMD");

        includedResourcesLabel.setText("Included resources");

        includedResourcesGroup.add(btnIncludeModelsAndTextures);
        btnIncludeModelsAndTextures.setSelected(true);
        btnIncludeModelsAndTextures.setText("Models and textures");

        includedResourcesGroup.add(btnIncludeModelsOnly);
        btnIncludeModelsOnly.setText("Models only");

        includedResourcesGroup.add(btnIncludeTexturesOnly);
        btnIncludeTexturesOnly.setText("Textures only (NSBTX)");

        additionalOptionsLabel.setText("Additional options");

        btnCreatePolystrips.setText("Create polygon strips");
        btnCreatePolystrips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePolystripsActionPerformed(evt);
            }
        });

        btnPreferVColOverNormal.setSelected(true);
        btnPreferVColOverNormal.setText("Prefer vertex colors over normals");

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        minPrimitiveCount.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));

        btnEnableMinPrimitiveCount.setText("Minumum primitive count:");
        btnEnableMinPrimitiveCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableMinPrimitiveCountActionPerformed(evt);
            }
        });

        btnIsOmitUnusedTextures.setText("Omit unused textures");

        btnJointsAsVisgroups.setSelected(true);
        btnJointsAsVisgroups.setText("Use joints as visibility groups");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExport))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnJointsAsVisgroups)
                            .addComponent(includedResourcesLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIncludeModelsOnly)
                                    .addComponent(btnIncludeModelsAndTextures)
                                    .addComponent(btnIncludeTexturesOnly)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(btnIsOmitUnusedTextures))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnEnableMinPrimitiveCount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minPrimitiveCount, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(additionalOptionsLabel)
                            .addComponent(btnPreferVColOverNormal)
                            .addComponent(btnCreatePolystrips))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(includedResourcesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncludeModelsAndTextures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIsOmitUnusedTextures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncludeModelsOnly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncludeTexturesOnly)
                .addGap(18, 18, 18)
                .addComponent(additionalOptionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreatePolystrips)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minPrimitiveCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnableMinPrimitiveCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPreferVColOverNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJointsAsVisgroups)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
		DialogOptionRemember.putRememberedCheckbox(btnCreatePolystrips);
		DialogOptionRemember.putRememberedCheckbox(btnEnableMinPrimitiveCount);
		DialogOptionRemember.putRememberedCheckbox(btnPreferVColOverNormal);
		DialogOptionRemember.putRememberedRBtnPos(includedResourcesGroup);
		DialogOptionRemember.putRememberedCheckbox(btnIsOmitUnusedTextures);
		DialogOptionRemember.putRememberedCheckbox(btnJointsAsVisgroups);
		DialogOptionRemember.putRememberedSpinner(minPrimitiveCount, "nsbmd_MinPrimitiveCount");

		result = new NSBMDExportSettings(
			btnIncludeModelsOnly.isSelected() || btnIncludeModelsAndTextures.isSelected(),
			btnIncludeTexturesOnly.isSelected() || btnIncludeModelsAndTextures.isSelected(),
			btnPreferVColOverNormal.isSelected(),
			btnCreatePolystrips.isSelected(),
			btnEnableMinPrimitiveCount.isSelected() ? (Integer)(minPrimitiveCount.getValue()) : -1,
			btnJointsAsVisgroups.isSelected(),
			btnIncludeModelsAndTextures.isSelected() ? btnIsOmitUnusedTextures.isSelected() : false
		);

		dispose();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnEnableMinPrimitiveCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableMinPrimitiveCountActionPerformed
		setModelOrTextureCheckboxEnabled();
    }//GEN-LAST:event_btnEnableMinPrimitiveCountActionPerformed

    private void btnCreatePolystripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePolystripsActionPerformed
		setModelOrTextureCheckboxEnabled();
    }//GEN-LAST:event_btnCreatePolystripsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel additionalOptionsLabel;
    private javax.swing.JCheckBox btnCreatePolystrips;
    private javax.swing.JCheckBox btnEnableMinPrimitiveCount;
    private javax.swing.JButton btnExport;
    private javax.swing.JRadioButton btnIncludeModelsAndTextures;
    private javax.swing.JRadioButton btnIncludeModelsOnly;
    private javax.swing.JRadioButton btnIncludeTexturesOnly;
    private javax.swing.JCheckBox btnIsOmitUnusedTextures;
    private javax.swing.JCheckBox btnJointsAsVisgroups;
    private javax.swing.JCheckBox btnPreferVColOverNormal;
    private javax.swing.ButtonGroup includedResourcesGroup;
    private javax.swing.JLabel includedResourcesLabel;
    private javax.swing.JSpinner minPrimitiveCount;
    // End of variables declaration//GEN-END:variables
}
