package ctrmap.creativestudio.nitroplugin;

import ctrmap.formats.ntr.nitroreader.nsbmd.NSBMDImportSettings;
import xstandard.gui.DialogOptionRemember;
import java.awt.Frame;

public class NSBMDImportDialog extends javax.swing.JDialog {

	private NSBMDImportSettings settings;
	
	public NSBMDImportDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);
		
		DialogOptionRemember.selectRememberedRBtnPos(primitivePrcsGroup);
		DialogOptionRemember.setRememberedCheckbox(btnSkinRgd2Smo);
		DialogOptionRemember.setRememberedCheckbox(btnMergeMeshesByMat);
	}
	
	public static NSBMDImportSettings getImportSettings(Frame parent){
		NSBMDImportDialog dlg = new NSBMDImportDialog(parent, true);
		dlg.setVisible(true);
		return dlg.settings;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primitivePrcsGroup = new javax.swing.ButtonGroup();
        btnImport = new javax.swing.JButton();
        primitivePrcsLabel = new javax.swing.JLabel();
        btnIsTriangulate = new javax.swing.JRadioButton();
        btnIsOnlyUnstrip = new javax.swing.JRadioButton();
        btnIsNoPrimitivePrcs = new javax.swing.JRadioButton();
        enhancementsLabel = new javax.swing.JLabel();
        btnSkinRgd2Smo = new javax.swing.JCheckBox();
        btnMergeMeshesByMat = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Import NSBMD");
        setResizable(false);

        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        primitivePrcsLabel.setText("Primitive processing");

        primitivePrcsGroup.add(btnIsTriangulate);
        btnIsTriangulate.setSelected(true);
        btnIsTriangulate.setText("Triangulate");

        primitivePrcsGroup.add(btnIsOnlyUnstrip);
        btnIsOnlyUnstrip.setText("Only unstrip");

        primitivePrcsGroup.add(btnIsNoPrimitivePrcs);
        btnIsNoPrimitivePrcs.setText("Keep as is");

        enhancementsLabel.setText("Enhancements");

        btnSkinRgd2Smo.setSelected(true);
        btnSkinRgd2Smo.setText("Rigid to smooth skinning");

        btnMergeMeshesByMat.setSelected(true);
        btnMergeMeshesByMat.setText("Merge meshes by materials");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 169, Short.MAX_VALUE)
                                .addComponent(btnImport))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primitivePrcsLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnIsOnlyUnstrip)
                                            .addComponent(btnIsTriangulate)
                                            .addComponent(btnIsNoPrimitivePrcs)))
                                    .addComponent(enhancementsLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMergeMeshesByMat)
                            .addComponent(btnSkinRgd2Smo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(primitivePrcsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIsTriangulate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIsOnlyUnstrip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIsNoPrimitivePrcs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enhancementsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSkinRgd2Smo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMergeMeshesByMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnImport)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        settings = new NSBMDImportSettings(btnIsOnlyUnstrip.isSelected(), btnIsTriangulate.isSelected(), btnSkinRgd2Smo.isSelected(), btnMergeMeshesByMat.isSelected());
		
		DialogOptionRemember.putRememberedRBtnPos(primitivePrcsGroup);
		DialogOptionRemember.putRememberedCheckbox(btnSkinRgd2Smo);
		DialogOptionRemember.putRememberedCheckbox(btnMergeMeshesByMat);
		
		dispose();
    }//GEN-LAST:event_btnImportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImport;
    private javax.swing.JRadioButton btnIsNoPrimitivePrcs;
    private javax.swing.JRadioButton btnIsOnlyUnstrip;
    private javax.swing.JRadioButton btnIsTriangulate;
    private javax.swing.JCheckBox btnMergeMeshesByMat;
    private javax.swing.JCheckBox btnSkinRgd2Smo;
    private javax.swing.JLabel enhancementsLabel;
    private javax.swing.ButtonGroup primitivePrcsGroup;
    private javax.swing.JLabel primitivePrcsLabel;
    // End of variables declaration//GEN-END:variables
}
