package ctrmap.editor.gui.editors.gen5.level.entities;

import ctrmap.editor.CTRMap;
import ctrmap.editor.gui.editors.common.AbstractTabbedEditor;
import ctrmap.editor.gui.editors.text.alias.ITextAliasManager;
import ctrmap.editor.gui.editors.gen5.text.VTextLoader;
import ctrmap.editor.system.script.CTRMapIDEHelper;
import ctrmap.pokescript.ide.PSIDE;
import ctrmap.pokescript.ide.system.project.IDEFile;
import ctrmap.pokescript.ide.system.project.IDEProject;
import ctrmap.pokescript.stage0.Preprocessor;
import ctrmap.pokescript.stage1.NCompileGraph;
import xstandard.fs.FSUtil;
import ctrmap.formats.common.GameInfoListener;
import ctrmap.pokescript.ide.FileEditorRSTA;
import xstandard.gui.file.XFileDialog;
import java.util.List;
import ctrmap.missioncontrol_ntr.field.VFieldController;
import ctrmap.missioncontrol_ntr.field.debug.VZoneDebugger;
import ctrmap.editor.system.script.MessageIDManager;
import ctrmap.editor.system.workspace.CTRMapProject;
import ctrmap.editor.system.workspace.UserData;
import ctrmap.formats.pokemon.gen5.zone.entities.VZoneEntities;
import ctrmap.missioncontrol_ntr.field.debug.VFieldDebugger;
import ctrmap.missioncontrol_ntr.field.script.FieldScriptConfigurator;
import ctrmap.missioncontrol_ntr.field.structs.VZone;
import ctrmap.pokescript.ide.system.IDEResourceReference;
import ctrmap.pokescript.ide.system.ResourcePathType;
import ctrmap.pokescript.ide.system.project.IDEProjectListener;
import ctrmap.pokescript.ide.system.project.include.Dependency;
import ctrmap.pokescript.ide.system.project.include.DependencyType;
import ctrmap.pokescript.stage2.VExecMaker;
import ctrmap.scriptformats.gen5.VScriptFile;
import ctrmap.util.gui.CMGUI;
import java.util.concurrent.atomic.AtomicBoolean;
import xstandard.fs.FSFile;

public class VEventEditor extends javax.swing.JPanel implements AbstractTabbedEditor, VFieldDebugger, VZoneDebugger {

	private CTRMap cm;

	private VZone zone;

	private VFieldController ctrl;

	private MessageIDManager msgIdMgr;

	public VEventEditor(CTRMap cm) {
		initComponents();
		textEditor.load(cm);
		this.cm = cm;
	}

	@Override
	public void onProjectLoaded(CTRMapProject cmproj) {
		if (cmproj == null) {
			textEditor.setMsgIdManager(msgIdMgr = null);
		} else {
			textEditor.initialize(new VTextLoader(cm));
			textEditor.setMsgIdManager(msgIdMgr = new MessageIDManager(cmproj));
		}
	}
	
	@Override
	public void onProjectUnloaded(CTRMapProject cmproj) {
		onProjectLoaded(null);
	}

	@Override
	public void attachField(VFieldController ctrl) {
		this.ctrl = ctrl;
	}

	@Override
	public void loadZone(VZone z) {
		zone = z;
		if (z != null) {
			textEditor.forceMsgFileLoad(VTextLoader.ArcType.SCRIPT_MSG, z.header.textFileID);
		} else {
			textEditor.forceMsgFileLoad(VTextLoader.ArcType.SYSTEM_MSG, 0);
		}
	}
	
	@Override
	public boolean store(boolean dialog) {
		if (zone != null) {
			final AtomicBoolean forceWriteZoneEntities = new AtomicBoolean(false);
			if (zone.initScrUnused != null) {
				if (!CMGUI.commonSaveDataSequence(cm, zone.initScrUnused.hash, dialog, "Initialization scripts", true, (() -> {
					zone.initScrUnused.writeToSourceFile();
					if (zone.entities != null) {
						zone.entities.initScr.setFrom(zone.initScrUnused);
						forceWriteZoneEntities.set(true);
					}
				}))) {
					return false;
				}
			}

			VZoneEntities e = zone.entities;
			if (e != null) {
				if (!CMGUI.commonSaveDataSequence(cm, e.monitor, dialog, "Zone entities", true, (() -> {
					e.write();
					forceWriteZoneEntities.set(false); //written anyway
				}))) {
					return false;
				}
				if (forceWriteZoneEntities.get()) {
					e.write();
				}
			}
		}
		return textEditor.store(dialog);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
	 * code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scriptPnl = new javax.swing.JPanel();
        btnOpenScrInIDE = new javax.swing.JButton();
        openScrIDEWarning = new javax.swing.JLabel();
        btnReplaceScripts = new javax.swing.JButton();
        btnAttemptDecompilerOnOpenScr = new javax.swing.JCheckBox();
        warnSep = new javax.swing.JSeparator();

        textEditor.setBorder(javax.swing.BorderFactory.createTitledBorder("Texts"));

        scriptPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Scripts"));

        btnOpenScrInIDE.setText("Open in IDE");
        btnOpenScrInIDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenScrInIDEActionPerformed(evt);
            }
        });

        openScrIDEWarning.setForeground(new java.awt.Color(255, 0, 0));
        openScrIDEWarning.setText("Warning: This can permanently destroy non-user-coded scripts. Proceed with caution.");

        btnReplaceScripts.setText("Replace script file");
        btnReplaceScripts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaceScriptsActionPerformed(evt);
            }
        });

        btnAttemptDecompilerOnOpenScr.setSelected(true);
        btnAttemptDecompilerOnOpenScr.setText("Attempt to decompile");

        warnSep.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout scriptPnlLayout = new javax.swing.GroupLayout(scriptPnl);
        scriptPnl.setLayout(scriptPnlLayout);
        scriptPnlLayout.setHorizontalGroup(
            scriptPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scriptPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReplaceScripts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOpenScrInIDE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAttemptDecompilerOnOpenScr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warnSep, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openScrIDEWarning)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        scriptPnlLayout.setVerticalGroup(
            scriptPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scriptPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openScrIDEWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warnSep)
                    .addGroup(scriptPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOpenScrInIDE)
                        .addComponent(btnAttemptDecompilerOnOpenScr)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReplaceScripts)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                    .addComponent(scriptPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scriptPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReplaceScriptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaceScriptsActionPerformed
		if (zone != null) {
			FSFile f = XFileDialog.openFileDialog();

			if (f != null) {
				FSUtil.copy(f, zone.scripts.getSourceFile());
			}
		}
    }//GEN-LAST:event_btnReplaceScriptsActionPerformed

	private class ZoneScriptsIDEProjectListener implements IDEProjectListener {

		private VScriptFile file;

		public ZoneScriptsIDEProjectListener(VScriptFile scriptFile) {
			this.file = scriptFile;
		}

		@Override
		public void onMainClassChanged(IDEFile newMainClass) {
			System.out.println("Project main class changed to " + newMainClass);
			changeWorkMainClass(newMainClass);
			onSaved(FileEditorRSTA.SaveResult.SAVED);
		}

		@Override
		public void onSaved(FileEditorRSTA.SaveResult result) {
			if (result != FileEditorRSTA.SaveResult.CANCELLED && lastMainClass != null) {
				IDEFile f = lastMainClass;
				Preprocessor pp = f.getCompiler();
				if (pp.isCompileSuccessful()) {
					NCompileGraph cg = f.getCompiler().getCompileGraph();
					if (cg != null) {
						VExecMaker.compileVScript(cg, file);
						file.write();
					}
				}
			}
		}
	}

	private IDEFile lastMainClass = null;

	private void changeWorkMainClass(IDEFile mainClass) {
		lastMainClass = mainClass;
	}

	private IDEProject lastProject = null;
	private ZoneScriptsIDEProjectListener projectListener;

	private void changeWorkProject(IDEProject project) {
		if (project != lastProject) {
			if (lastProject != null) {
				lastProject.removeListener(projectListener);
			}
			lastProject = project;
			project.addListener(projectListener = new ZoneScriptsIDEProjectListener(zone.scripts));
		}
	}

    private void btnOpenScrInIDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenScrInIDEActionPerformed
		if (zone != null) {
			CTRMapIDEHelper.ProjectSetupParam psp;
			if (btnAttemptDecompilerOnOpenScr.isSelected()) {
				psp = new CTRMapIDEHelper.ZoneEventProjectSetupParam5Decomp(
					zone.id, 
					zone.header.textFileID,
					zone.scripts,
					FieldScriptConfigurator.ScriptPluginConfig.getOverlayIDs(ctrl.scrConfigs.getCfgForZone(zone.id)),
					cm.getGame(),
					cm.ideHelper
				);
			} else {
				psp = new CTRMapIDEHelper.ZoneEventProjectSetupParam5(zone.id, zone.header.textFileID, cm.getGame());
			}
			msgIdMgr.updateIncludeByTag(new ITextAliasManager.MessageTag(VTextLoader.ArcType.SCRIPT_MSG, zone.header.textFileID, -1));
			IDEProject project = cm.ideHelper.getOrCreateProject(psp);

			PSIDE ide = cm.ideHelper.getIDE();
			ide.openProject(project);

			Dependency dep = new Dependency(DependencyType.DIRECTORY);
			dep.ref = new IDEResourceReference(ResourcePathType.ON_DISK, cm.getProject().userData.getUserDataDir(UserData.UsrDirectory.SCRIPT_INCLUDE).getPath());
			project.addDependency(ide.context, dep);

			ide.resyncProject(project);
			IDEFile mainClass = project.getMainClass();

			if (mainClass != null) {
				ide.openFile(mainClass);
				mainClass = ide.getAlreadyOpenedFile(mainClass);
			} else {
				System.out.println("Warn: project has no main class.");
			}

			changeWorkMainClass(mainClass);
			changeWorkProject(project);

			ide.setVisible(true);
		}
    }//GEN-LAST:event_btnOpenScrInIDEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnAttemptDecompilerOnOpenScr;
    private javax.swing.JButton btnOpenScrInIDE;
    private javax.swing.JButton btnReplaceScripts;
    private javax.swing.JLabel openScrIDEWarning;
    private javax.swing.JPanel scriptPnl;
    public final ctrmap.editor.gui.editors.text.TextEditor textEditor = new ctrmap.editor.gui.editors.text.TextEditor();
    private javax.swing.JSeparator warnSep;
    // End of variables declaration//GEN-END:variables

	@Override
	public String getTabName() {
		return "Event Editor";
	}

	@Override
	public List<GameInfoListener> getGameInfoListeners() {
		return textEditor.getGameInfoListeners();
	}
}
