package ctrmap.editor.gui.editors.gen5.level.entities;

import ctrmap.editor.gui.editors.gen5.level.VLevelEditor;
import ctrmap.editor.gui.editors.gen5.level.tools.VProxyTool;
import ctrmap.editor.gui.editors.common.tools.AbstractTool;
import ctrmap.formats.common.GameInfoListener;
import xstandard.gui.components.ComponentUtils;
import xstandard.gui.components.PlusMinusButtonSet;
import xstandard.util.ArraysEx;
import ctrmap.util.gui.CMGUI;
import java.util.ArrayList;
import java.util.List;
import ctrmap.formats.pokemon.gen5.zone.entities.VFurniture;
import ctrmap.missioncontrol_ntr.field.VFieldController;
import ctrmap.missioncontrol_ntr.field.debug.VZoneDebugger;
import ctrmap.missioncontrol_ntr.field.structs.VZone;
import ctrmap.editor.gui.editors.common.AbstractToolbarEditor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class VProxyEditor extends javax.swing.JPanel implements AbstractToolbarEditor, VZoneDebugger {

	private VProxyTool tool;
	public VZone zone;
	public VLevelEditor editors;

	private boolean loaded = false;
	public VFurniture furniture;

	public VProxyEditor(VLevelEditor editors) {
		initComponents();
		this.editors = editors;

		tool = new VProxyTool(this);

		ComponentUtils.setNFValueClass(Integer.class, condition);

		addRemove.addListener(new PlusMinusButtonSet.PMButtonListener() {
			@Override
			public void plusClicked() {
				if (zone != null && zone.entities != null) {
					CMGUI.addToComboBoxAndListWorldObjSimple(new VFurniture(), zone.entities.furniture, furnitureComboBox, editors);
				}
			}

			@Override
			public void minusClicked() {
				if (zone != null && zone.entities != null) {
					CMGUI.removeFromComboBoxAndList(furniture, zone.entities.furniture, furnitureComboBox);
				}
			}
		});
		
		locPanel.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (furniture != null) {
					VRailOrGridLocationPanel.PositionSet ps = locPanel.save();
					furniture.isPositionRail = ps.isPositionRail;
					furniture.railLineNo = ps.railLineID;
					furniture.railFrontPos = ps.railPosFront;
					furniture.railSidePos = ps.railPosSide;
					furniture.gridX = ps.gridX;
					furniture.gridZ = ps.gridZ;
					furniture.y = (int) ps.worldY;
				}
			}
		});
	}

	public void setFurniture(int index) {
		ComponentUtils.setSelectedIndexSafe(furnitureComboBox, index);
	}

	private void showFurniture(int index) {
		if (zone != null && index >=0 && index < zone.entities.furniture.size()) {
			furniture = zone.entities.furniture.get(index);

			VFurniture f = furniture;
			scrid.setValue(f.script);

			locPanel.load(new VRailOrGridLocationPanel.PositionSet(f.isPositionRail, f.gridX, f.y, f.gridZ, f.railLineNo, f.railFrontPos, f.railSidePos));

			condition.setValue(f.condition);
			interactibility.setSelectedIndex(f.interactibility);
		}
		else {
			furniture = null;
			ComponentUtils.clearComponents(scrid, condition, interactibility);
			locPanel.load(null);
		}
		tool.setSelectedObject(furniture);
	}

	public void saveFurniture() {
		if (this.furniture != null) {
			VFurniture f = this.furniture;
			f.script = (Integer) scrid.getValue();
			f.condition = (Integer) this.condition.getValue();
			f.interactibility = interactibility.getSelectedIndex();
		}
	}

	public void refreshNoSave() {
		showFurniture(furnitureComboBox.getSelectedIndex());
	}

	@Override
	public List<AbstractTool> getTools() {
		return ArraysEx.asList(tool);
	}

	@Override
	public void loadZone(VZone z) {
		this.zone = z;

		loaded = false;
		furniture = null;
		furnitureComboBox.removeAllItems();
		int i = 0;
		if (z != null) {
			for (VFurniture f : z.entities.furniture) {
				furnitureComboBox.addItem(String.valueOf(i));
				i++;
			}
		}
		tool.fullyRebuildScene();
		loaded = true;
		setFurniture(0);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        furnitureComboBox = new javax.swing.JComboBox<>();
        mainSep = new javax.swing.JSeparator();
        entityPanel = new javax.swing.JPanel();
        scridLabel = new javax.swing.JLabel();
        scrid = new javax.swing.JSpinner();
        entSep = new javax.swing.JSeparator();
        locLabel = new javax.swing.JLabel();
        locPanel = new ctrmap.editor.gui.editors.gen5.level.entities.VRailOrGridLocationPanel();
        furniturePanel = new javax.swing.JPanel();
        condition = new javax.swing.JFormattedTextField();
        conditionLabel = new javax.swing.JLabel();
        interactibilityLabel = new javax.swing.JLabel();
        interactibility = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        addRemove = new xstandard.gui.components.PlusMinusButtonSet();

        furnitureComboBox.setMaximumRowCount(25);
        furnitureComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                furnitureComboBoxActionPerformed(evt);
            }
        });

        entityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Entity"));

        scridLabel.setText("Script");

        scrid.setModel(new javax.swing.SpinnerNumberModel());

        locLabel.setText("Location");

        javax.swing.GroupLayout entityPanelLayout = new javax.swing.GroupLayout(entityPanel);
        entityPanel.setLayout(entityPanelLayout);
        entityPanelLayout.setHorizontalGroup(
            entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(entSep)
                    .addGroup(entityPanelLayout.createSequentialGroup()
                        .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(entityPanelLayout.createSequentialGroup()
                                .addComponent(scridLabel)
                                .addGap(44, 44, 44)
                                .addComponent(scrid, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(locLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        entityPanelLayout.setVerticalGroup(
            entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scridLabel)
                    .addComponent(scrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entSep, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        furniturePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Furniture"));

        condition.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        conditionLabel.setText("Condition");
        conditionLabel.setToolTipText("");

        interactibilityLabel.setText("Interactibility");

        interactibility.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "South", "West", "East", "North", "All", "West/East", "North/South" }));

        javax.swing.GroupLayout furniturePanelLayout = new javax.swing.GroupLayout(furniturePanel);
        furniturePanel.setLayout(furniturePanelLayout);
        furniturePanelLayout.setHorizontalGroup(
            furniturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(furniturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(furniturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interactibilityLabel)
                    .addComponent(conditionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(furniturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(condition, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(interactibility, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        furniturePanelLayout.setVerticalGroup(
            furniturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(furniturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(furniturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conditionLabel)
                    .addComponent(condition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(furniturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interactibilityLabel)
                    .addComponent(interactibility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainSep)
                    .addComponent(furniturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(furnitureComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(furnitureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(furniturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void furnitureComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_furnitureComboBoxActionPerformed
		if (this.loaded) {
			saveFurniture();
			showFurniture(furnitureComboBox.getSelectedIndex());
		}
    }//GEN-LAST:event_furnitureComboBoxActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
		saveFurniture();
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private xstandard.gui.components.PlusMinusButtonSet addRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JFormattedTextField condition;
    private javax.swing.JLabel conditionLabel;
    private javax.swing.JSeparator entSep;
    private javax.swing.JPanel entityPanel;
    private javax.swing.JComboBox<String> furnitureComboBox;
    private javax.swing.JPanel furniturePanel;
    private javax.swing.JComboBox<String> interactibility;
    private javax.swing.JLabel interactibilityLabel;
    private javax.swing.JLabel locLabel;
    private ctrmap.editor.gui.editors.gen5.level.entities.VRailOrGridLocationPanel locPanel;
    private javax.swing.JSeparator mainSep;
    private javax.swing.JSpinner scrid;
    private javax.swing.JLabel scridLabel;
    // End of variables declaration//GEN-END:variables
}
