package ctrmap.editor.gui.editors.gen5.level.entities;

import ctrmap.editor.gui.editors.gen5.level.VLevelEditor;
import ctrmap.editor.gui.editors.gen5.level.tools.VTriggerTool;
import ctrmap.editor.gui.editors.common.tools.AbstractTool;
import xstandard.gui.components.ComponentUtils;
import xstandard.gui.components.PlusMinusButtonSet;
import xstandard.util.ArraysEx;
import ctrmap.util.gui.CMGUI;
import java.util.List;
import ctrmap.formats.pokemon.gen5.zone.entities.VTrigger;
import ctrmap.missioncontrol_ntr.field.VFieldController;
import ctrmap.missioncontrol_ntr.field.debug.VZoneDebugger;
import ctrmap.missioncontrol_ntr.field.structs.VZone;
import ctrmap.editor.gui.editors.common.AbstractToolbarEditor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class VTriggerEditor extends javax.swing.JPanel implements AbstractToolbarEditor, VZoneDebugger {

	private VTriggerTool tool;
	public VZone zone;
	public VLevelEditor editors;

	private boolean loaded = false;
	public VTrigger trigger;

	public VTriggerEditor(VLevelEditor editors) {
		initComponents();
		this.editors = editors;

		tool = new VTriggerTool(this);

		ComponentUtils.setNFValueClass(Integer.class, h, w, u12);

		addRemove.addListener(new PlusMinusButtonSet.PMButtonListener() {
			@Override
			public void plusClicked() {
				if (zone != null && zone.entities != null) {
					CMGUI.addToComboBoxAndListWorldObjSimple(new VTrigger(), zone.entities.triggers, triggerComboBox, editors);
				}
			}

			@Override
			public void minusClicked() {
				if (zone != null && zone.entities != null) {
					CMGUI.removeFromComboBoxAndList(trigger, zone.entities.triggers, triggerComboBox);
				}
			}
		});
		
		locPanel.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (trigger != null) {
					VRailOrGridLocationPanel.PositionSet ps = locPanel.save();
					trigger.isRail = ps.isPositionRail;
					trigger.gridX = ps.gridX;
					trigger.gridZ = ps.gridZ;
					trigger.worldY = (int) ps.worldY;
					trigger.railLineNo = ps.railLineID;
					trigger.railPosFront = ps.railPosFront;
					trigger.railPosSide = ps.railPosSide;
				}
			}
		});
	}

	public void setTrigger(int index) {
		ComponentUtils.setSelectedIndexSafe(triggerComboBox, index);
	}

	private void showTrigger(int index) {
		if (zone != null && index >= 0 && index < zone.entities.triggers.size()) {
			trigger = zone.entities.triggers.get(index);

			VTrigger t = trigger;
			spawnFlag.setValue(t.wkId);
			refVal.setValue(t.wkRefVal);
			scrid.setValue(t.script);

			locPanel.load(new VRailOrGridLocationPanel.PositionSet(t.isRail, t.gridX, t.worldY, t.gridZ, t.railLineNo, t.railPosFront, t.railPosSide));

			w.setValue(t.w);
			h.setValue(t.h);

			triggerType.setSelectedIndex(t.type.ordinal());
			u12.setValue(t.unk0x12);
		}
		else {
			ComponentUtils.clearComponents(spawnFlag, refVal, scrid, w, h, u12);
			locPanel.load(null);
			trigger = null;
		}
		
		tool.setSelectedObject(trigger);
	}

	public void saveTrigger() {
		if (this.trigger != null) {
			VTrigger t = this.trigger;

			t.wkId = (Integer) spawnFlag.getValue();
			t.wkRefVal = (Integer) refVal.getValue();
			t.script = (Integer) scrid.getValue();

			t.w = (Integer) w.getValue();
			t.h = (Integer) h.getValue();

			t.type = VTrigger.Type.values()[triggerType.getSelectedIndex()];
			t.unk0x12 = (Integer) u12.getValue();
		}
	}

	public void refreshNoSave() {
		showTrigger(triggerComboBox.getSelectedIndex());
	}

	@Override
	public List<AbstractTool> getTools() {
		return ArraysEx.asList(tool);
	}

	@Override
	public void loadZone(VZone z) {
		this.zone = z;

		loaded = false;
		trigger = null;
		triggerComboBox.removeAllItems();
		if (z != null) {
			int i = 0;
			for (VTrigger trigger : z.entities.triggers) {
				triggerComboBox.addItem(String.valueOf(i));
				i++;
			}
		}
		tool.fullyRebuildScene();
		loaded = true;
		setTrigger(0);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        triggerComboBox = new javax.swing.JComboBox<>();
        mainSep = new javax.swing.JSeparator();
        entityPanel = new javax.swing.JPanel();
        spawnFlagLabel = new javax.swing.JLabel();
        spawnFlag = new javax.swing.JSpinner();
        scridLabel = new javax.swing.JLabel();
        scrid = new javax.swing.JSpinner();
        entSep = new javax.swing.JSeparator();
        locLabel = new javax.swing.JLabel();
        refValLabel = new javax.swing.JLabel();
        refVal = new javax.swing.JSpinner();
        dimLabel = new javax.swing.JLabel();
        wLabel = new javax.swing.JLabel();
        w = new javax.swing.JFormattedTextField();
        hLabel = new javax.swing.JLabel();
        h = new javax.swing.JFormattedTextField();
        locPanel = new ctrmap.editor.gui.editors.gen5.level.entities.VRailOrGridLocationPanel();
        miscPanel = new javax.swing.JPanel();
        u6Label = new javax.swing.JLabel();
        u12Label = new javax.swing.JLabel();
        u12 = new javax.swing.JFormattedTextField();
        triggerType = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        addRemove = new xstandard.gui.components.PlusMinusButtonSet();

        triggerComboBox.setMaximumRowCount(25);
        triggerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triggerComboBoxActionPerformed(evt);
            }
        });

        entityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Entity"));

        spawnFlagLabel.setText("Spawn flag");

        spawnFlag.setModel(new javax.swing.SpinnerNumberModel());

        scridLabel.setText("Script");

        scrid.setModel(new javax.swing.SpinnerNumberModel());

        locLabel.setText("Location");

        refValLabel.setText("Ref. value");

        refVal.setModel(new javax.swing.SpinnerNumberModel());

        dimLabel.setText("Dimensions");

        wLabel.setForeground(new java.awt.Color(255, 0, 0));
        wLabel.setText("Width");

        w.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        hLabel.setForeground(new java.awt.Color(0, 153, 0));
        hLabel.setText("Height");

        h.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout entityPanelLayout = new javax.swing.GroupLayout(entityPanel);
        entityPanel.setLayout(entityPanelLayout);
        entityPanelLayout.setHorizontalGroup(
            entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entSep)
                    .addComponent(locPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(entityPanelLayout.createSequentialGroup()
                        .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locLabel)
                            .addGroup(entityPanelLayout.createSequentialGroup()
                                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(entityPanelLayout.createSequentialGroup()
                                        .addComponent(spawnFlagLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(spawnFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(entityPanelLayout.createSequentialGroup()
                                        .addComponent(scridLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(scrid, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refValLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refVal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dimLabel)
                            .addGroup(entityPanelLayout.createSequentialGroup()
                                .addComponent(wLabel)
                                .addGap(13, 13, 13)
                                .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(entityPanelLayout.createSequentialGroup()
                                .addComponent(hLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        entityPanelLayout.setVerticalGroup(
            entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scridLabel)
                    .addComponent(scrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spawnFlagLabel)
                    .addComponent(spawnFlag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refValLabel)
                    .addComponent(refVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entSep, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entityPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(hLabel))
                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        miscPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Misc."));

        u6Label.setText("Type");
        u6Label.setToolTipText("");

        u12Label.setText("U12");

        u12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        triggerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Directional (Up)", "Directional (Down)", "Directional (Left)", "Directional (Right)", "Inactive", "Colliding", "Type 7" }));

        javax.swing.GroupLayout miscPanelLayout = new javax.swing.GroupLayout(miscPanel);
        miscPanel.setLayout(miscPanelLayout);
        miscPanelLayout.setHorizontalGroup(
            miscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miscPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(miscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, miscPanelLayout.createSequentialGroup()
                        .addComponent(u6Label)
                        .addGap(4, 4, 4))
                    .addGroup(miscPanelLayout.createSequentialGroup()
                        .addComponent(u12Label)
                        .addGap(9, 9, 9)))
                .addGroup(miscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(u12)
                    .addComponent(triggerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        miscPanelLayout.setVerticalGroup(
            miscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miscPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(miscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u6Label)
                    .addComponent(triggerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u12Label)
                    .addComponent(u12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainSep)
                    .addComponent(miscPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(triggerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(triggerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miscPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void triggerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triggerComboBoxActionPerformed
		if (loaded) {
			saveTrigger();
			showTrigger(triggerComboBox.getSelectedIndex());
		}
    }//GEN-LAST:event_triggerComboBoxActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
		saveTrigger();
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private xstandard.gui.components.PlusMinusButtonSet addRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel dimLabel;
    private javax.swing.JSeparator entSep;
    private javax.swing.JPanel entityPanel;
    private javax.swing.JFormattedTextField h;
    private javax.swing.JLabel hLabel;
    private javax.swing.JLabel locLabel;
    private ctrmap.editor.gui.editors.gen5.level.entities.VRailOrGridLocationPanel locPanel;
    private javax.swing.JSeparator mainSep;
    private javax.swing.JPanel miscPanel;
    private javax.swing.JSpinner refVal;
    private javax.swing.JLabel refValLabel;
    private javax.swing.JSpinner scrid;
    private javax.swing.JLabel scridLabel;
    private javax.swing.JSpinner spawnFlag;
    private javax.swing.JLabel spawnFlagLabel;
    private javax.swing.JComboBox<String> triggerComboBox;
    private javax.swing.JComboBox<String> triggerType;
    private javax.swing.JFormattedTextField u12;
    private javax.swing.JLabel u12Label;
    private javax.swing.JLabel u6Label;
    private javax.swing.JFormattedTextField w;
    private javax.swing.JLabel wLabel;
    // End of variables declaration//GEN-END:variables
}
