package ctrmap.editor.gui.editors.gen5.level.entities;

import ctrmap.editor.gui.editors.gen5.level.VLevelEditor;
import ctrmap.editor.gui.editors.gen5.level.tools.VWarpTool;
import ctrmap.editor.gui.editors.common.tools.AbstractTool;
import ctrmap.formats.common.GameInfoListener;
import xstandard.gui.components.ComponentUtils;
import xstandard.gui.components.PlusMinusButtonSet;
import xstandard.util.ArraysEx;
import ctrmap.util.gui.CMGUI;
import java.util.ArrayList;
import java.util.List;
import ctrmap.formats.pokemon.gen5.zone.entities.VTrigger;
import ctrmap.formats.pokemon.gen5.zone.entities.VWarp;
import ctrmap.missioncontrol_ntr.field.VFieldController;
import ctrmap.missioncontrol_ntr.field.debug.VZoneDebugger;
import ctrmap.missioncontrol_ntr.field.structs.VZone;
import ctrmap.editor.gui.editors.common.AbstractToolbarEditor;

public class VWarpEditor extends javax.swing.JPanel implements AbstractToolbarEditor, VZoneDebugger {

	private VWarpTool tool;
	public VZone zone;
	public VLevelEditor editors;

	private boolean loaded = false;
	public VWarp warp;

	public VWarpEditor(VLevelEditor editors) {
		initComponents();
		this.editors = editors;

		tool = new VWarpTool(this);

		ComponentUtils.setNFValueClass(Integer.class, h, w, transition, targetWarp, targetZone);

		addRemove.addListener(new PlusMinusButtonSet.PMButtonListener() {
			@Override
			public void plusClicked() {
				if (zone != null && zone.entities != null) {
					CMGUI.addToComboBoxAndListWorldObjSimple(new VWarp(), zone.entities.warps, warpComboBox, editors);
				}
			}

			@Override
			public void minusClicked() {
				if (zone != null && zone.entities != null) {
					CMGUI.removeFromComboBoxAndList(warp, zone.entities.warps, warpComboBox);
				}
			}
		});

		locPanel.addActionListener((e) -> {
			if (warp != null) {
				VRailOrGridLocationPanel.PositionSet pos = locPanel.save();
				warp.isRail = pos.isPositionRail;
				warp.x = pos.gridX;
				warp.y = (int) pos.worldY;
				warp.z = pos.gridZ;
				warp.railLineNo = pos.railLineID;
				warp.railPosFront = pos.railPosFront;
				warp.railPosSide = pos.railPosSide;
			}
		});
	}

	public void setWarp(int index) {
		ComponentUtils.setSelectedIndexSafe(warpComboBox, index);
	}

	private void showWarp(int index) {
		if (zone != null && index < zone.entities.warps.size() && index >= 0) {
			warp = zone.entities.warps.get(index);

			VWarp w = warp;
			locPanel.load(new VRailOrGridLocationPanel.PositionSet(w.isRail, w.x, w.y, w.z, w.railLineNo, w.railPosFront, w.railPosSide));
			contactDirection.setSelectedIndex(w.faceDirection.ordinal());
			this.w.setValue(w.w);
			h.setValue(w.h);
			transition.setValue(w.transitionType);
			targetWarp.setValue(w.targetWarpId);
			targetZone.setValue(w.targetZone);
		} else {
			ComponentUtils.clearComponents(contactDirection, w, h, transition, targetWarp, targetZone);
			locPanel.load(null);

			warp = null;
		}

		tool.setSelectedObject(warp);
	}

	public void saveWarp() {
		if (warp != null) {
			VWarp w = warp;
			w.faceDirection = VWarp.ContactDirection.values()[contactDirection.getSelectedIndex()];
			w.w = (Integer) this.w.getValue();
			w.h = (Integer) h.getValue();
			w.transitionType = (Integer) transition.getValue();
			w.targetWarpId = (Integer) targetWarp.getValue();
			w.targetZone = (Integer) targetZone.getValue();
		}
	}

	public void refreshNoSave() {
		showWarp(warpComboBox.getSelectedIndex());
	}

	@Override
	public List<AbstractTool> getTools() {
		return ArraysEx.asList(tool);
	}

	@Override
	public void loadZone(VZone z) {
		this.zone = z;

		loaded = false;
		warpComboBox.removeAllItems();
		warp = null;
		if (z != null) {
			int i = 0;
			for (VWarp warp : z.entities.warps) {
				warpComboBox.addItem(String.valueOf(i));
				i++;
			}
		}
		tool.fullyRebuildScene();
		loaded = true;
		setWarp(0);
	}
	
	@Override
	public void prepareForSave() {
		saveWarp();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
	 * code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warpComboBox = new javax.swing.JComboBox<>();
        mainSep = new javax.swing.JSeparator();
        entityPanel = new javax.swing.JPanel();
        dimLabel = new javax.swing.JLabel();
        wLabel = new javax.swing.JLabel();
        w = new javax.swing.JFormattedTextField();
        hLabel = new javax.swing.JLabel();
        h = new javax.swing.JFormattedTextField();
        locPanel = new ctrmap.editor.gui.editors.gen5.level.entities.VRailOrGridLocationPanel();
        warpPanel = new javax.swing.JPanel();
        transition = new javax.swing.JFormattedTextField();
        u6Label = new javax.swing.JLabel();
        u8Label = new javax.swing.JLabel();
        targetZone = new javax.swing.JFormattedTextField();
        u12Label = new javax.swing.JLabel();
        targetWarp = new javax.swing.JFormattedTextField();
        u6Label1 = new javax.swing.JLabel();
        contactDirection = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        addRemove = new xstandard.gui.components.PlusMinusButtonSet();

        warpComboBox.setMaximumRowCount(25);
        warpComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warpComboBoxActionPerformed(evt);
            }
        });

        entityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Entity"));

        dimLabel.setText("Dimensions");

        wLabel.setForeground(new java.awt.Color(255, 0, 0));
        wLabel.setText("Width");

        w.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        hLabel.setForeground(new java.awt.Color(0, 153, 0));
        hLabel.setText("Height");

        h.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout entityPanelLayout = new javax.swing.GroupLayout(entityPanel);
        entityPanel.setLayout(entityPanelLayout);
        entityPanelLayout.setHorizontalGroup(
            entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entityPanelLayout.createSequentialGroup()
                        .addComponent(locPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(entityPanelLayout.createSequentialGroup()
                        .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dimLabel)
                            .addGroup(entityPanelLayout.createSequentialGroup()
                                .addComponent(wLabel)
                                .addGap(13, 13, 13)
                                .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(entityPanelLayout.createSequentialGroup()
                                .addComponent(hLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        entityPanelLayout.setVerticalGroup(
            entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(locPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(entityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entityPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(hLabel))
                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        warpPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Warp"));

        transition.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        u6Label.setText("Transition type");
        u6Label.setToolTipText("");

        u8Label.setText("Target zone");

        targetZone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        u12Label.setText("Target warp");

        targetWarp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        u6Label1.setText("Contact direction");
        u6Label1.setToolTipText("");

        contactDirection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "North", "South", "West", "East" }));

        javax.swing.GroupLayout warpPanelLayout = new javax.swing.GroupLayout(warpPanel);
        warpPanel.setLayout(warpPanelLayout);
        warpPanelLayout.setHorizontalGroup(
            warpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(warpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(targetZone, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(warpPanelLayout.createSequentialGroup()
                        .addGroup(warpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(u6Label)
                            .addComponent(u8Label)
                            .addComponent(u12Label)
                            .addComponent(u6Label1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(warpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(transition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(targetWarp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(contactDirection, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        warpPanelLayout.setVerticalGroup(
            warpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(warpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u6Label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(warpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u6Label)
                    .addComponent(transition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(warpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u8Label)
                    .addComponent(targetZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(warpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u12Label)
                    .addComponent(targetWarp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainSep)
                    .addComponent(warpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(warpComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(warpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void warpComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warpComboBoxActionPerformed
		if (loaded) {
			saveWarp();
			showWarp(warpComboBox.getSelectedIndex());
		}
    }//GEN-LAST:event_warpComboBoxActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
		saveWarp();
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private xstandard.gui.components.PlusMinusButtonSet addRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> contactDirection;
    private javax.swing.JLabel dimLabel;
    private javax.swing.JPanel entityPanel;
    private javax.swing.JFormattedTextField h;
    private javax.swing.JLabel hLabel;
    private ctrmap.editor.gui.editors.gen5.level.entities.VRailOrGridLocationPanel locPanel;
    private javax.swing.JSeparator mainSep;
    private javax.swing.JFormattedTextField targetWarp;
    private javax.swing.JFormattedTextField targetZone;
    private javax.swing.JFormattedTextField transition;
    private javax.swing.JLabel u12Label;
    private javax.swing.JLabel u6Label;
    private javax.swing.JLabel u6Label1;
    private javax.swing.JLabel u8Label;
    private javax.swing.JFormattedTextField w;
    private javax.swing.JLabel wLabel;
    private javax.swing.JComboBox<String> warpComboBox;
    private javax.swing.JPanel warpPanel;
    // End of variables declaration//GEN-END:variables
}
